version: '3.8'

services:
  init:
    image: alpine
    container_name: initializer
    volumes:
      - /opt/mysql:/opt/mysql
      - /opt/emqx:/opt/emqx
      - /opt/nginx:/opt/nginx
      - /opt/init:/opt/init
    entrypoint: ["/bin/sh", "/opt/init/init.sh"]
    restart: "no"

  mysql:
    image: mysql:8.4.5
    container_name: mysql8
    restart: always
    depends_on:
      - init
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Lc#.68!2025
    volumes:
      - /opt/mysql/data:/var/lib/mysql
      - /opt/mysql/conf:/etc/mysql/conf.d

  redis:
    image: redis:6.2.18
    container_name: redis6
    restart: always
    depends_on:
      - init
    ports:
      - "6379:6379"
    volumes:
      - /opt/redis/data:/data
    command: redis-server --appendonly yes --requirepass Lc#.68!2025

  nginx:
    image: nginx:1.20.2
    container_name: nginx1
    restart: always
    depends_on:
      - init
    ports:
      - "80:80"
    volumes:
      - /opt/nginx/html:/usr/share/nginx/html
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/nginx/conf.d:/etc/nginx/conf.d
      - /opt/nginx/log:/var/log/nginx

  emqx:
    image: emqx/emqx-enterprise:5.10.0
    container_name: emqx
    restart: always
    depends_on:
      - init
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
      - "8883:8883"
      - "8084:8084"
    volumes:
      - /opt/emqx/data:/opt/emqx/data
      - /opt/emqx/log:/opt/emqx/log